// Generated by delombok at Sun Mar 03 12:53:28 CET 2024
package dev.tiltrikt.web3j.spring.boot.starter.configuration;

import org.jetbrains.annotations.NotNull;
import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "web3j")
public class StarterWeb3jProperties {
  @NotNull
  private String network = "https://testnet.ton.dev";
  @NotNull
  private String contract = "0xAD4AdD81B11b4951c87bdb2eb0F4aC8e0fE06712";
  private int decimals = 18;

  @NotNull
  @java.lang.SuppressWarnings("all")
  public String getNetwork() {
    return this.network;
  }

  @NotNull
  @java.lang.SuppressWarnings("all")
  public String getContract() {
    return this.contract;
  }

  @java.lang.SuppressWarnings("all")
  public int getDecimals() {
    return this.decimals;
  }

  @java.lang.SuppressWarnings("all")
  public void setNetwork(@NotNull final String network) {
    if (network == null) {
      throw new java.lang.NullPointerException("network is marked non-null but is null");
    }
    this.network = network;
  }

  @java.lang.SuppressWarnings("all")
  public void setContract(@NotNull final String contract) {
    if (contract == null) {
      throw new java.lang.NullPointerException("contract is marked non-null but is null");
    }
    this.contract = contract;
  }

  @java.lang.SuppressWarnings("all")
  public void setDecimals(final int decimals) {
    this.decimals = decimals;
  }
}
